name: MatrixCreator

run-name: "Creates supported family matrix for other jobs"

on:
  workflow_call:
    outputs:
      matrix:
        description: "Supported family for job matrixing"
        value: ${{ jobs.CreateMatrix.outputs.matrix }}

jobs:
  CreateMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v4

      - name: Create matrix
        id: create-matrix
        run: |
          families=$(sed -nr "s@stm32_util_create_family_targets\((\w+)+(\s\w+)?\)@\1@p" cmake/stm32/* | tr -d '\r' | sort  | uniq)
          echo "matrix={\"family\":$(jq --compact-output --null-input '$ARGS.positional' --args -- ${families[@]})}" >> $GITHUB_OUTPUT
